### ISSUE TITLE
Incorrect URLs built if a Path with a leading / is used

### ISSUE THREAD

**Issue by sazzer** [steverydz/build-url#1]
Great little module for building URLs. However, I've just discovered that if I try to build a URL with only a path, and the path starts with a leading / then it does the wrong thing.

```
        const url = buildUrl({
            path: '/w',
            queryParams: {
                q: searchData.query,
                count: searchData.pageSize,
                sort: searchData.sort || '',
                offset
            }
        });
```

It turns out that, inside the buildUrl function, this actually writes a URL to `//w?q=......`, which the browser then (correctly) interprets as a URL to the host "w" instead of to the path "/w".

**Comment by steverydz** [comment]
Thanks for raising this. Unfortunately I didn't get a notification about this issue so it went unnoticed (will check my Github settings now!). This recent PR (https://github.com/steverydz/build-url/pull/2) takes care of this.
