### ISSUE TITLE
addition of encoding query params is a breaking change

### ISSUE THREAD

**Issue by shaicantor** [steverydz/build-url#16]
Hey,
you added the encoding of query params in the version 1.1.2 [here](https://github.com/steverydz/build-url/commit/0bdc4dd36804af4fbd6162be2b274188c96edcdc)
This is a breaking change, since I was encoding query params myself and now I get double encoding.

**Comment by steverydz** [comment]
Thank you for raising this issue. I agree that this shouldn't have been a patch release. My apologies. Can you work around the issue for now by locking your dependency to the previous version?
