### ISSUE TITLE
how to avoid @ replace in queryparams.

### ISSUE THREAD

**Issue by manpreetgillsride** [steverydz/build-url#19]
@ replace in url %40 so how to avoid this issue.

**Comment by steverydz** [comment]
I'm not sure I understand what you mean? Can you please give some context? Perhaps a code example?

**Comment by manpreetgillsride** [comment]
encode queryparams avoid. (?r=yy%20zz&c=hh%40op)
correct (?r=yy zz&c=hh@op)

**Comment by steverydz** [comment]
Right, so if I understand correctly you want the formatted URL to return an unencoded URL?

If so this library doesn't support that. If this is what you want to can run the formatted URL through the `decodeURI` method. [See docs on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI)
