### ISSUE TITLE
Expose TypeScript declarations or post to DefinitelyTyped

### ISSUE THREAD

**Issue by mbohgard** [steverydz/build-url#22]
The typings you provide (build-url.d.ts) is not picked up by any compiler since it's not [referenced in package.json](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).
Also, since build-url is built in JavaScript, typings should be commited to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) rather than bundled with the module.

Mention typings author: @recurrence

**Comment by steverydz** [comment]
Thank you for flagging this up. I'll add `build-url.d.ts` to `package.json` and then close the issue.

I took a quick look at DefinitelyTyped but it's not clear what purpose it serves or how it would relate to this library? I'm not a TS user so perhaps I'm missing something obvious?

**Comment by mbohgard** [comment]
@steverydz Ok, so DefinitelyTyped is a Microsoft backed repo with typings for all open source projects that are not written in TypeScript. If you want to provide typings to your project for TypeScript users to benefit from, you should have them bundled with the module IF it's written in TypeScript. If not (like with build-url) you should post the type declarations to DefinitelyTyped. That's the idea and best practice at least.
