### ISSUE TITLE
Support an array of path elements

### ISSUE THREAD

**Issue by leonard84** [steverydz/build-url#26]
I'd like to be able to write something like

```javascript
buildUrl('http://example.com', {
  path: ['about','me'],  
});
```
which would join all path elements with a '/', e.g. `http://example.com/about/me`

**Comment by steverydz** [comment]
@leonard84 I think it's better to pass in the whole path as a string. If you really want to use an array I'd suggest you do something along the lines of:

```
var path = ["about", "me"].join("/");

buildUrl("http://example.com", {
  path: path
});
```
