### ISSUE TITLE
Trailing slash is stripped from the base URL if no path is given

### ISSUE THREAD

**Issue by jonathanj** [steverydz/build-url#27]
```javascript
// No options.
console.log(buildUrl('http://example.com/api/v2/'));
// => http://example.com/api/v2

// Empty path option.
console.log(buildUrl('http://example.com/api/v2/', {path: ''}));
// => http://example.com/api/v2

// Explicit path that is only a slash.
console.log(buildUrl('http://example.com/api/v2/', {path: '/'}));
// => http://example.com/api/v2/
```

A trailing slash is significant and the two distinct cases represent two different resources, I don't think this library should be manipulating the base URL when no path is given.

**Comment by steverydz** [comment]
@jonathanj Thanks for filing an issue.

I agree that the URL should not be manipulated in this way. I'll try to get a fix out when I have time.
