### ISSUE TITLE
cannot find module 'build-url' v5.0.1

### ISSUE THREAD

**Issue by Clumsy-Coder** [steverydz/build-url#41]
Can't seem to resolve module

```js
import buildUrl from 'build-url';
```

v3.0.0 -> v5.0.1

**Comment by Clumsy-Coder** [comment]
Also missing type definitions 

check https://github.com/steverydz/build-url/issues/39

**Comment by steverydz** [comment]
Thanks for filing this bug. 5.0.2 fixes this.

In regards to the type definitions please see https://github.com/steverydz/build-url/issues/39#issuecomment-683443462

Thanks
