### ISSUE TITLE
main file entry in package.json should have dist path, not src

### ISSUE THREAD

**Issue by Treverix** [steverydz/build-url#42]
The last fix for 5.0.2 broke something, we now see the error

```
Error: Cannot find module 'C:\dev\prj\udemy\serapis\node_modules\build-url\src\build-url.js'. Please verify that the package.json has a valid "main" entry
```

The entry should be `"main": "./dist/build-url.js"`

**Comment by Treverix** [comment]
https://github.com/steverydz/build-url/pull/43

**Comment by steverydz** [comment]
Thanks for the PR. I've decided to roll this back to v3.0.0 which was the last stable version of this project, so v6.0.0 is essentially the same thing.
