### ISSUE TITLE
Query param values are not URL encoded

### ISSUE THREAD

**Issue by jtaylor10** [steverydz/build-url#5]
URL params cannot contain reserved characters yet the library does not encode values.

Example Input:
```
{
  queryParams: {
    test: 'test&'
  }
}
```

Expected Output:
```
?test=test%26
```

Actual Output
```
?test=test&
```

**Comment by michelbl** [comment]
I now use `querystring.stringify()` because of that very issue.

**Comment by jtaylor10** [comment]
Yeah it's an easy workaround - I'm using `encodeURIComponent` as it affects keys as well so building the query param object up like...
```javascript
const qp = {};
qp[encodeURIComponent(myParamName)] = encodeURIComponent(myParamValue);
```

**Comment by steverydz** [comment]
This makes sense to add into the project. Feel free to make a PR. If not I will add this when I get time.
