### ISSUE TITLE
Support passing an object into queryParams, similar to $.param

### ISSUE THREAD

**Issue by nicknish** [steverydz/build-url#6]
Support passing an object into queryParams, similar to $.param.

Current:

```javascript
buildUrl('', {
  queryParams: {
    foo: {
      bar: 'baz'
    }
  }
});

// => ?foo=[object Object]
```

Expected:

```javascript
// => foo%5Bbar%5D=baz
```

**Comment by steverydz** [comment]
This seems like it would be a good enhancement. Feel free to make a PR. If not I'll look at implementing this when I get time.

**Comment by steverydz** [comment]
Fixed by https://github.com/steverydz/build-url/pull/13
